language: julia

os: linux

julia:
  - 1.5

notifications:
  email: false

install:
  - gem install coveralls-lcov
  - julia --project --color=yes -e 'using Pkg; Pkg.instantiate()'

script:
  - travis_wait 20 julia --project --color=yes -e 'using Pkg; Pkg.test("OpenStreetMapX")'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; LCOV.writefile("coverage-lcov.info", process_folder())'
  - coveralls-lcov -v --repo-token=$COVERALLS_TOKEN --service-name=travis-pro coverage-lcov.info
